#---------------------------------------------------------------------
# GitHub Action Workflow DevOps HomeWork 
#
# Version      Date        Info
# 1.0          2022        Initial Version
#
# Made by Vladislav Vicol Copyleft (c) 2022
#---------------------------------------------------------------------
name: my-homework-indrivo
env:
  APPLICATION_NAME    : "MyApp"
  DEPLOY_PACKAGE_NAME : "app-ver-${{ github.sha }}"
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - name: Git clone my repo
    - uses: actions/checkout@v1
      run : ls
    - working-directory: /src
    
    - name: Dotnet build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - copy:
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
